In [5]:
! python -m pip install numpy


     ---------------------------------------- 0.0/14.9 MB ? eta -:--:--
     --------------------------------------- 0.0/14.9 MB 991.0 kB/s eta 0:00:15
     ---------------------------------------- 0.1/14.9 MB 1.3 MB/s eta 0:00:12
     ---------------------------------------- 0.2/14.9 MB 1.1 MB/s eta 0:00:13
      --------------------------------------- 0.2/14.9 MB 1.2 MB/s eta 0:00:13
      --------------------------------------- 0.3/14.9 MB 1.4 MB/s eta 0:00:11
     - -------------------------------------- 0.4/14.9 MB 1.5 MB/s eta 0:00:10
     - -------------------------------------- 0.5/14.9 MB 1.4 MB/s eta 0:00:11
     - -------------------------------------- 0.5/14.9 MB 1.4 MB/s eta 0:00:11
     - -------------------------------------- 0.6/14.9 MB 1.4 MB/s eta 0:00:11
     - -------------------------------------- 0.7/14.9 MB 1.5 MB/s eta 0:00:10
     -- ------------------------------------- 0.8/14.9 MB 1.6 MB/s eta 0:00:09
     -- ------------------------------------- 0.9/14.9 MB 


[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
a = np.array([8,6,50])

In [8]:
print(a.shape)

(3,)


In [11]:
b=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
b

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [12]:
b.shape

(4, 3)

In [13]:
m= np.array ([ [[4,41],[8,81],[7,71]   ],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [14]:
m.shape

(3, 3, 2)

In [18]:
print(b[0:5:1,2].shape)


(4,)


In [19]:
print(b[0:,-1:])

[[ 4]
 [ 5]
 [17]
 [ 8]]


In [20]:
print(b[:,2:3])

[[ 4]
 [ 5]
 [17]
 [ 8]]


In [22]:
print(m[1:,1:,:1])

[[[ 1]
  [ 5]]

 [[ 9]
  [13]]]


In [30]:
print(m[:,2:,:2])

[[[  7  71]]

 [[  5  51]]

 [[ 13 131]]]


In [31]:
print(b+5)

[[ 8 13  9]
 [14  8 10]
 [16 20 22]
 [24 36 13]]


In [34]:
b[0:,-2]= [80,30,150,301]
b

array([[  3,  80,   4],
       [  9,  30,   5],
       [ 11, 150,  17],
       [ 19, 301,   8]])

In [44]:
b[1:,1:]=[[202,303],[404,505],[606,707]]
b

array([[  3,  80,   4],
       [  9, 202, 303],
       [ 11, 404, 505],
       [ 19, 606, 707]])

In [46]:
np.append(b,[[1],[1],[1],[1]],axis=1)

array([[  3,  80,   4,   1],
       [  9, 202, 303,   1],
       [ 11, 404, 505,   1],
       [ 19, 606, 707,   1]])

In [37]:
np.append(b,[[1,1,1]],axis=0)

array([[  3,  80,   4],
       [  9, 202, 303],
       [ 11, 404, 505],
       [ 19, 606, 707],
       [  1,   1,   1]])

In [47]:
np.delete(b,1,0)

array([[  3,  80,   4],
       [ 11, 404, 505],
       [ 19, 606, 707]])

In [48]:
np.delete(b,1,1)

array([[  3,   4],
       [  9, 303],
       [ 11, 505],
       [ 19, 707]])

In [50]:
np.delete(b,3,axis=0)

array([[  3,  80,   4],
       [  9, 202, 303],
       [ 11, 404, 505]])

In [53]:
b.reshape(6,2)

array([[  3,  80],
       [  4,   9],
       [202, 303],
       [ 11, 404],
       [505,  19],
       [606, 707]])

In [52]:
b.reshape(2,3,2)

array([[[  3,  80],
        [  4,   9],
        [202, 303]],

       [[ 11, 404],
        [505,  19],
        [606, 707]]])

In [54]:
b.astype(float)

array([[  3.,  80.,   4.],
       [  9., 202., 303.],
       [ 11., 404., 505.],
       [ 19., 606., 707.]])

In [55]:
b.astype('uint16')

array([[  3,  80,   4],
       [  9, 202, 303],
       [ 11, 404, 505],
       [ 19, 606, 707]], dtype=uint16)

In [56]:
b.std(axis=1)

array([ 36.06475657, 121.9681197 , 213.09517957, 303.33589743])

In [2]:
import numpy as np
np.arange(0,14,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [1]:
import numpy as np
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [3]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
list(range(1,11,1))
np.random.randint(1,6,1)

array([1])

In [7]:
np.random.randint(31,6000,[4,3],)

array([[4516, 3814, 2388],
       [3427, 3278,  676],
       [3571, 1410, 2375],
       [ 679, 1503, 4384]])

In [ ]:
np.random.seed(54 )
np.random.randint(31,6000,[4,3],)

In [8]:
np.random.rand(3,4)

array([[0.18257357, 0.32489741, 0.20012194, 0.83842052],
       [0.71818363, 0.3227067 , 0.51009485, 0.30870266],
       [0.45365054, 0.45320644, 0.70792212, 0.73112701]])

In [10]:
p=np.random.rand(3,4)
p

array([[0.99526441, 0.17407258, 0.88437933, 0.59893446],
       [0.90627257, 0.85241513, 0.15854067, 0.97277876],
       [0.45453148, 0.18016926, 0.45721961, 0.56780794]])

In [11]:
np.savetxt('new.txt',p,delimiter=',')

In [9]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['hii,', 'this', 'is', 'first', 'yext', 'file.'], dtype='<U5')

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.randn(26)

array([-0.84700706,  0.21093977, -0.1742217 ,  0.54518509, -0.20904688,
       -0.49399575, -0.98693534,  0.40359528,  0.74932459,  1.35751664,
        0.55124729, -1.42806965, -0.32263894, -0.39466442,  2.15353333,
        2.28050583,  0.2357761 ,  0.97080686, -1.17017468,  0.59803659,
       -0.53893345,  0.13885962,  1.67791659, -0.79526576, -1.17005032,
        0.57137   ])

In [ ]:
np.arange(0.01,1.01,0.01),reshape(10,10)