In [7]:
import numpy as np


In [14]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.shape

(2, 3)

In [16]:
m= np.array([1,2,3])
print(m)


[1 2 3]


In [17]:
b= np.zeros([0,0])
b

array([], shape=(0, 0), dtype=float64)

In [19]:
a=np.ones([1,1])
a

array([[1.]])

In [23]:
np.arange(0,14,2)


array([ 0,  2,  4,  6,  8, 10, 12])